Implement Annotator for TLS validation
project-alvarium/alvarium-sdk-java pull request #47
Opened 2021-09-09 13:21 UTC by KarimElghamry

* Add TLS AnnotationType
* Implement TlsAnnotator to validate TLS connection
  and sign the produced annotation
* Add AnnotatorUtils class to govern the common operations
  done by all annotators
* Add TlsAnnotator to the AnnotatorFactory
* Implement related unit test

Fix #43

Signed-off-by: Karim Elghamry <karimelghamry@gmail.com>

2021-09-09 13:23 UTC, KarimElghamry commented on src/main/java/com/alvarium/contracts/AnnotationType.java
>  public enum AnnotationType {
The rest of the enum serializations are implemented in the PR #46. Once it's merge, I will rebase and resolve conflicts.

2021-09-10 21:59 UTC, tsconn23 commented
@KarimElghamry Resolve conflicts when you can via rebase, and then I'll take a look at this one.

2021-09-10 22:16 UTC, KarimElghamry commented
> 
> 
> @KarimElghamry Resolve conflicts when you can via rebase, and then I'll take a look at this one.

Rebased in 90b81f6c5b8b0cbd6a944fc2898949a6bfdcbd38

2021-09-10 23:03 UTC, tsconn23 requested changes

2021-09-13 08:29 UTC, KarimElghamry commented on src/main/java/com/alvarium/annotators/TlsAnnotator.java
> +    final Annotation annotation = new Annotation(key, hash, host, kind, null, isStatified,
I don't know what happened when I was typing this. must've been the vim key bindings being messed up inside of vscode. fixed in 00386d7feec721a46ad75d0b380d5db0b109a1fb

2021-09-13 08:29 UTC, KarimElghamry commented on src/main/java/com/alvarium/annotators/AnnotatorUtils.java
> + */
makes sense. I think this approach is cleaner. fixed in 00386d7feec721a46ad75d0b380d5db0b109a1fb

2021-09-13 08:29 UTC, KarimElghamry commented on src/main/java/com/alvarium/annotators/TlsAnnotator.java
> +    Boolean isStatified = this.verfiyHandshake(ctx.getProperty(AnnotationType.TLS.name(),
fixed in 00386d7feec721a46ad75d0b380d5db0b109a1fb

2021-09-13 08:31 UTC, KarimElghamry commented on src/main/java/com/alvarium/contracts/Annotation.java
> +      return new Annotation(this.id, this.key, this.hash, this.host, this.kind, sig, this.isSatisfied
I was aiming for absolute immutability. Yea, I think a normal setter would be enough in our usecase. setter added in 00386d7feec721a46ad75d0b380d5db0b109a1fb

2021-09-13 21:59 UTC, tsconn23 approved these changes

2021-09-13 21:59 UTC, merged